server:
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      username: handy
      password: handy
      database: handy
  profiles:
    include:
      - kakao